branch-defaults:
  default:
    environment: come-again-dev
global:
  application_name: come-again
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: null
